### ISSUE TITLE
RTC DS1307 reading/writing data broken

### ISSUE THREAD

**Issue by maxxir** [feilipu/avrfreertos#10]
I've got next problem:
Can't read and set-up RTC DS1307, timestamp get/set broken data!
(Different boards check: mega328p, mega644p, mega1284p - result failure here on feilipu avrfreeRTOS RTC,
but on Arduino simple scatch from Adafruit DS1307 RTC lib (on the same hardware) - works without error..)
After spent some time for debug, the next bug catch:

../freeRTOS82x/lib_rtc/rtc.c

```
uint8_t decToBcd(uint8_t val)
..
    return ( ((uint16_t)val*16/10) + (val%10) ); //This is reason of bug!!
```
    
```
uint8_t bcdToDec(uint8_t val)
..
    return ( ((uint16_t)val*10/16) + (val%16) ); //This is reason of bug!!
```
    

After change this funcs to fix error:
    
```
// Convert normal decimal number byte to binary coded decimal byte
uint8_t decToBcd(uint8_t val)
{
    //return ( ((uint16_t)val*16/10) + (val%10) );
    return ( (val/10*16) + (val%10) );
}

// Convert binary coded decimal byte to normal decimal number byte
uint8_t bcdToDec(uint8_t val)
{
    //return ( ((uint16_t)val*10/16) + (val%16) );
    return ( (val/16*10) + (val%16) );
}
```

All works without error.
Regards maxxir

**Comment by feilipu** [comment]
Fixed with [this](https://github.com/feilipu/avrfreertos/commit/b592cf34d429c2c06c7c191c061a4799557715fe) commit.
