### ISSUE TITLE
10.1.1 release?

### ISSUE THREAD

**Issue by iorbitearth** [feilipu/avrfreertos#11]
The latest release is from Dec 2017, but there have been some patches in the last few months I believe related to FreeRTOS 10.1.1.

Any interest in creating a new release? I typically like to pin submodules to official release tags :-)

**Comment by feilipu** [comment]
10.2.0 is now the latest version, so I might do a release soon. Once it’s bug tested.

**Comment by feilipu** [comment]
v10.3.0 now done. Let's do a release.
