### ISSUE TITLE
Bug on the serial flush for SIM900 uIP

### ISSUE THREAD

**Issue by xtysing** [feilipu/avrfreertos#4]
There should be xSerialRxFlush() instead of xSerialFlush() in the line 98 of IINChip_uIP_Test/lib_SIM900.c , the line 99 of TouchPhone/lib_SIM900.c , the line 169 of TouchPhone/main.c, the line 172 and the line 194 of KermitServer/avrio.c

**Comment by feilipu** [comment]
Thanks for the notes.
I'll fix these issues in the Repository.

Just to note that the code examples come from different phases of evolution of the main freeRTOS platform, and hence are not up to date (and may not actually work as expected).
