### ISSUE TITLE
Low power mode

### ISSUE THREAD

**Issue by FrozenDroid** [feilipu/avrfreertos#7]
Hey, just a question here.

How would I put the chip (atmega2560 in this case) into a low power mode of sorts?
Is there an example out there, how to do this with this port of FreeRTOS?

**Comment by feilipu** [comment]
Yes, there are some tools for that which are described in the [Hackster.io post on battery power](https://www.hackster.io/feilipu/battery-powered-arduino-applications-through-freertos-3b7401).
You need to call the sleep api from the [IdleTask hook](https://github.com/feilipu/Arduino_FreeRTOS_Library/blob/e82fd92d03c458130f5f33f300e646e0c3fc73ef/src/variantHooks.cpp#L73) as in the [example in Hackster.io code](https://www.hackster.io/feilipu/battery-powered-arduino-applications-through-freertos-3b7401#code).
But, you don't need to put the Arduino `loop()` function in between, as shown in the examples from Arduino_FreeRTOS_Library.
