### ISSUE TITLE
Garbled serial after sleep

### ISSUE THREAD

**Issue by FrozenDroid** [feilipu/avrfreertos#9]
Hi, according to #7, I am trying to use `set_sleep_mode( SLEEP_MODE_PWR_SAVE );` in my Idle task hook, but if the idle task ever gets a chance to run, it sleeps and after that, the serial ports start transmitting garbled data... Any idea what I could be doing wrong?

**Comment by FrozenDroid** [comment]
To clarify, this happens with every sleep mode except idle.

**Comment by feilipu** [comment]
I don't think you're doing anything wrong. I've noted a similar issue myself.
This "feature" is not advised in the AVR documentation, to my knowledge.

I've only been able to work around it by re-initialising the serial ports when waking up the MCU.

**Comment by FrozenDroid** [comment]
I've got it to kind of work by conditionally going into idle or power save depending on whether serial data needs to be sent. Still some garbage data here and there but it's very minimal. Still not good enough to control devices with AT commands, but I could maybe improve upon it.

**Comment by feilipu** [comment]
Let us know if you find a reliable way to address it, please.
Initialising and flushing the serial ports each wake-up event is a poor (though workable) solution, IMHO.

**Comment by FrozenDroid** [comment]
I think I may have a solution, but there's a few limitations. First off, you can only receive serial data if the device you're talking to supports flow control. Second, in https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/tasks.c#L3279 you say that it must not call a function that blocks. Is a ~80us delay okay (depending on baud rate...)? I need it to make the flow control work.
I'll share my solution once it's proven stable.
Also, it doesn't work with 2x mode, for some reason... I'll look into this.

**Comment by feilipu** [comment]
The comment about blocking (particularly with disabled interrupts) comes via Richard. A blocking Idle task will ensure that the scheduler cannot run. I think that in practical terms, if you are sleeping or waking from sleep then this reality could be neglected as part of a practical solution.
